### This is a notebook where i am trying some experiments on data preporcessing to enhance my understandability of data pre-processing.

##### 3 main strategies
1 Drop — remove rows or columns with too many nulls. Simple but loses data.

2 Fill with a statistic — use mean/median for numbers, mode for categories.

3 Predict (imputation) — use another model to estimate the missing value.

In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer

## Performing operations on missing values

In [2]:
df = pd.read_csv('./Datasets/Advertising Budget and Sales.csv')

df.head()

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9

In [3]:
# Detect missing values
print(df.isnull().sum())

Unnamed: 0                 0
TV Ad Budget ($)           0
Radio Ad Budget ($)        0
Newspaper Ad Budget ($)    0
Sales ($)                  0
dtype: int64

In [5]:
# Strategty 1: drop rows with any null
df_dropped = df.dropna()
df_dropped

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9
...,...,...,...,...,...
195,196,38.2,3.7,13.8,7.6
196,197,94.2,4.9,8.1,9.7
197,198,177.0,9.3,6.4,12.8
198,199,283.6,42.0,66.2,25.5
199,200,232.1,8.6,8.7,13.4

In [16]:
# Strategy 2: fill with median
imputer = SimpleImputer(strategy='median')
df['Sales ($)'] = imputer.fit_transform(df[['Sales ($)']])
df

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9
...,...,...,...,...,...
190,191,39.5,41.1,5.8,10.8
193,194,166.8,42.0,3.6,19.6
194,195,149.7,35.6,6.0,17.3
195,196,38.2,3.7,13.8,7.6
199,200,232.1,8.6,8.7,13.4

## Working on duplicates

In [15]:
#How Many duplicates
print(df.duplicated().sum())
df

0

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9
...,...,...,...,...,...
190,191,39.5,41.1,5.8,10.8
193,194,166.8,42.0,3.6,19.6
194,195,149.7,35.6,6.0,17.3
195,196,38.2,3.7,13.8,7.6
199,200,232.1,8.6,8.7,13.4

In [ ]:
# See the duplicate rows
print(df[df.duplicated(keep=False)])

Empty DataFrame
Columns: [Unnamed: 0, TV Ad Budget ($), Radio Ad Budget ($), Newspaper Ad Budget ($), Sales ($)]
Index: []

In [14]:
# Remove exact duplicates (keep first)
df = df.drop_duplicates()
df

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9
...,...,...,...,...,...
190,191,39.5,41.1,5.8,10.8
193,194,166.8,42.0,3.6,19.6
194,195,149.7,35.6,6.0,17.3
195,196,38.2,3.7,13.8,7.6
199,200,232.1,8.6,8.7,13.4

In [12]:
# Remove duplicates by specific columns
df = df.drop_duplicates(subset=['Radio Ad Budget ($)'])

In [13]:
df

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9
...,...,...,...,...,...
190,191,39.5,41.1,5.8,10.8
193,194,166.8,42.0,3.6,19.6
194,195,149.7,35.6,6.0,17.3
195,196,38.2,3.7,13.8,7.6
199,200,232.1,8.6,8.7,13.4

## Encoding

In [18]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({'color': ['Red','Blue','Green','Red'],
                   'size':  ['S','M','L','M']})

# One-hot encoding (no false order)
df_encoded = pd.get_dummies(df, columns=['color'])

# Label encoding (only for ordinal data)
le = LabelEncoder()
size_order = {'S': 0, 'M': 1, 'L': 2}
df['size_enc'] = df['size'].map(size_order)
df

   color size  size_enc
0    Red    S         0
1   Blue    M         1
2  Green    L         2
3    Red    M         1