### Hi, I am using this notebook to enhance my understanding of decision trees.
#### My main agenda is to use the iris dataset to implement the Decision tree algorithm

In [12]:
import pandas as pd
df = pd.read_csv("./Dataset/iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [13]:
inputs = df.drop("species", axis="columns")
target = df["species"]

inputs

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [14]:
target

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
LabelEncoder()

le_sepal_length = LabelEncoder()
le_sepal_width = LabelEncoder()
le_petal_length = LabelEncoder()
le_petal_width = LabelEncoder()

In [21]:
inputs['sepal_length_'] = pd.Series(
	le_sepal_length.fit_transform(inputs['sepal_length']),
	index=inputs.index,
	dtype='int64'
)
inputs['sepal_width_'] = pd.Series(
	le_sepal_width.fit_transform(inputs['sepal_width']),
	index=inputs.index,
	dtype='int64'
)
inputs['petal_length_'] = pd.Series(
	le_petal_length.fit_transform(inputs['petal_length']),
	index=inputs.index,
	dtype='int64'
)
inputs['petal_width_'] = pd.Series(
	le_petal_width.fit_transform(inputs['petal_width']),
	index=inputs.index,
	dtype='int64'
)


inputs.head()

,sepal_length,sepal_width,petal_length,petal_width,sepal_length_,sepal_width_,petal_length_,petal_width_
0,8,14,4,1,8,14,4,1
1,6,9,4,1,6,9,4,1
2,4,11,3,1,4,11,3,1
3,3,10,5,1,3,10,5,1
4,7,15,4,1,7,15,4,1

In [24]:
input_n = inputs.drop(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], axis='columns')

input_n

     sepal_length_  sepal_width_  petal_length_  petal_width_
0                8            14              4             1
1                6             9              4             1
2                4            11              3             1
3                3            10              5             1
4                7            15              4             1
..             ...           ...            ...           ...
145             24             9             28            19
146             20             4             26            15
147             22             9             28            16
148             19            13             30            19
149             16             9             27            14

[150 rows x 4 columns]

In [27]:
from sklearn import tree
from sklearn.model_selection import train_test_split


model = tree.DecisionTreeClassifier()

In [28]:
X = input_n
y = target

### Train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state=42)